language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

# Build
script:
- docker --version
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-frontend ./udagram-frontend
- docker build -t udagram-reverseproxy ./udagram-reverseproxy
- docker tag udagram-api-feed julianbhub/udagram-api-feed:v1
- docker tag udagram-api-user julianbhub/udagram-api-user:v1
- docker tag udagram-frontend julianbhub/udagram-frontend:v1
- docker tag udagram-reverseproxy julianbhub/reverseproxy:v1

# Push
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push julianbhub/udagram-api-feed:v1
- docker push julianbhub/udagram-api-user:v1
- docker push julianbhub/udagram-frontend:v1
- docker push julianbhub/reverseproxy:v1