# Build
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-frontend ./udagram-frontend
- docker build -t udagram-reverseproxy ./udagram-reverseproxy

# Tagging
- docker tag udagram-api-feed julianhub/udagram-api-feed:v1
- docker tag udagram-api-user julianhub/udagram-api-user:v1
- docker tag udagram-frontend julianhub/udagram-frontend:v1
- docker tag udagram-reverseproxy julianhub/reverseproxy:v1

# Push
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push udagram-api-feed julianhub/udagram-api-feed:v1
- docker push udagram-api-user julianhub/udagram-api-user:v1
- docker push udagram-frontend julianhub/udagram-frontend:v1
- docker push udagram-reverseproxy julianhub/reverseproxy:v1